services:
    laravel.test:
        build:
            context: .
            dockerfile: Dockerfile.prod
            args:
                WWWGROUP: '1000'
        image: 'seekrecruit/app'
        container_name: seekrecruit
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '3008:80'
        env_file:
            - .env
        environment:
            WWWUSER: '1000'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: 'off'
        volumes:
            - '.:/var/www/html'
        networks:
            - shared
        restart: unless-stopped

networks:
    shared:
        external: true
